version: '3'
services:
  php:
    build: ./docker/php
    volumes:
      - .:/src
    working_dir: /src
    environment:
      - TEST_RABBITMQ_HOST=rabbitmq
      - TOXIPROXY_HOST=proxy
      - TOXIPROXY_AMQP_PORT=5673
    depends_on:
      - rabbitmq
    entrypoint: ['tail', '-f', '/dev/null']
    links:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq